/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_example_huzhengbiao_jnidemo_MyJniUtils */

#ifndef _Included_com_example_huzhengbiao_jnidemo_MyJniUtils
#define _Included_com_example_huzhengbiao_jnidemo_MyJniUtils
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_example_huzhengbiao_jnidemo_MyJniUtils
 * Method:    getName
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_example_huzhengbiao_jnidemo_MyJniUtils_getName
  (JNIEnv *env, jobject);

#ifdef __cplusplus
}
#endif
#endif
